[build]
  publish = "public"
  command = "hugo -b https://grizzlygeek.net"

  [build.environment]
    HUGO_VERSION = "0.121.2"

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"